version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 5
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure_report:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  qaa_exam:
    build: .
    volumes:
      - ./pages:/test_app/pages
      - ./tests:/test_app/tests
      - ./allure-results:/test_app/allure-results
    depends_on:
      - chrome

  chrome:
    image: "selenium/standalone-chrome:120.0"
    shm_size: '2g'
    ports:
      - "4444:4444"
      - "7900:7900"

